### ISSUE TITLE
CSS Source

### ISSUE THREAD

**Issue by sdhunt** [EdwardMcveigh/prj-rev-bwfs-dasmoto#4]
The CSS is formatted nicely with appropriate indentation of, and whitespace between, each of the CSS rules.

There is, however, unnecessary duplication that should be removed:
https://github.com/EdwardMcveigh/prj-rev-bwfs-dasmoto/blob/master/dasmotos/css/style.css#L18-L37

You can define a common CSS class with the styles to apply to each `<h2>` elements, in addition to the distinct styles for each. For example:
```
.section h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

.brushes h2 {
  background-color: mediumspringgreen;
}

.frames h2 {
  background-color: lightcoral;
}

.paint h2 {
  background-color: skyblue;
}
```
And adding the common `section` class to each of the sections in the HTML:
```
    <div class="brushes section">
      <h2>Brushes</h2>
      ...
    </div>

    <div class="frames section">
      <h2>Frames</h2>
      ...
    </div>

    <div class="paint section">
      <h2>Paint</h2>
      ...
    </div>
```
Note that the value of the `class` attribute, when space-delimited, is treated as a list of CSS classes to apply to that element.

**Comment by Vanilladelphia** [comment]
Thank you for this comment! I knew there was a better way to do this, but I just couldn't figure out how.
